## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
df.drop(['EIN', 'NAME'], axis=1, inplace=True, errors='ignore')
df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Determine the number of unique values in each column.
df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
df.APPLICATION_TYPE.value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T15        2
T29        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(df.APPLICATION_TYPE.value_counts()[df.APPLICATION_TYPE.value_counts() < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    df['APPLICATION_TYPE'] = df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
df.CLASSIFICATION.value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
df['CLASSIFICATION'].value_counts()[df['CLASSIFICATION'].value_counts() > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(df.CLASSIFICATION.value_counts()[df.CLASSIFICATION.value_counts() < 10].index)

# Replace in dataframe
for cls in classifications_to_replace:
    df['CLASSIFICATION'] = df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Other       98
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
df_d = pd.get_dummies(df)
df_d.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [10]:
# Split our preprocessed data into our features and target arrays
y = df_d.IS_SUCCESSFUL
X = df_d.drop('IS_SUCCESSFUL', axis=1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_feats = len(X_train.columns)
h_layer1 = 80
h_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=h_layer1, input_dim=input_feats, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=h_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_2 (Dense)             (None, 80)                5440

 dense_3 (Dense)             (None, 30)                2430

 dense_4 (Dense)             (None, 1)                 31

=================================================================
Total params: 7901 (30.86 KB)
Trainable params: 7901 (30.86 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [17]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [19]:
# Train the model
train_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 4s 3ms/step - loss: 0.5676 - accuracy: 0.7236
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5529 - accuracy: 0.7315
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7326
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5472 - accuracy: 0.7339
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7337
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5447 - accuracy: 0.7348
Epoch 7/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5438 - accuracy: 0.7344
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5433 - accuracy: 0.7370
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7371
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7356
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7357
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7375
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5399 - accuracy: 0.7369
Epoch 14/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5398 - accuracy: 0.7375
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7384
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7376
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7383
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7389
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7393
Epoch 20/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5378 - accuracy: 0.7391
Epoch 21/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5379 - accuracy: 0.7390
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7396
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7395
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7404
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7404
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7402
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5358 - accuracy: 0.7413
Epoch 28/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5358 - accuracy: 0.7416
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7404
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7401
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7410
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7414
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7421
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7416
Epoch 35/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5342 - accuracy: 0.7418
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7411
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7416
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7417
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7414
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7416
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7426
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5331 - accuracy: 0.7414
Epoch 43/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5326 - accuracy: 0.7417
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7416
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7423
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7416
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7422
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7420
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7416
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5327 - accuracy: 0.7419
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5320 - accuracy: 0.7423
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7425
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7420
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7425
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5324 - accuracy: 0.7420
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7425
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7418
Epoch 58/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5315 - accuracy: 0.7421
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7424
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7427
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5315 - accuracy: 0.7421
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5316 - accuracy: 0.7427
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7426
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7432
Epoch 65/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5314 - accuracy: 0.7432
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5311 - accuracy: 0.7426
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5311 - accuracy: 0.7425
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5311 - accuracy: 0.7425
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5307 - accuracy: 0.7423
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5310 - accuracy: 0.7427
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5310 - accuracy: 0.7432
Epoch 72/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5303 - accuracy: 0.7429
Epoch 73/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5305 - accuracy: 0.7435
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7432
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5309 - accuracy: 0.7423
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5304 - accuracy: 0.7431
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7425
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5301 - accuracy: 0.7433
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5304 - accuracy: 0.7429
Epoch 80/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5305 - accuracy: 0.7434
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7424
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5301 - accuracy: 0.7430
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5300 - accuracy: 0.7432
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7430
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5301 - accuracy: 0.7432
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7432
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5299 - accuracy: 0.7431
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5299 - accuracy: 0.7435
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7432
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7443
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7432
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7431
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7435
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5297 - accuracy: 0.7435
Epoch 95/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5294 - accuracy: 0.7436
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7432
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7432
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7426
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7432
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7438

In [21]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5592 - accuracy: 0.7252 - 350ms/epoch - 1ms/step
Loss: 0.5592115521430969, Accuracy: 0.7252478003501892

In [22]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(